### PR TITLE
DOCS: add a __version__ attribute (2)

### PR DESCRIPTION
**Pull request by antoinecollet5**
See #132 

Sorry for the two previous PR that were not clean.

### CODE REVIEW

**Comment by tommyod** [comment]
Thanks @antoinecollet5 ! Linting and typing is failing. Probably very easy to fix :)

Apart from the linting and typing, I think this is a great addition. Most packages expose a `__version__` attribute.

**Comment by antoinecollet5** [comment]
Thanks for you feed back :) !

Hummm, appearly I forgot to install pre-commit in the repo when  I cloned it. Fixed.

**Review by tommyod — APPROVED** [review]

**Comment by dafeda** [comment]
Thanks, this looks good 👍 

Please squash the commits into one.
By the way, we try to follow this guideline for how to write commit messages: https://cbea.ms/git-commit/

**Comment by tommyod** [comment]
I merged it now (and squashed on merge for him :) )

Thanks again @antoinecollet5 !

**Pull request merged**
