### PR TITLE
ENH: Add Makefile to .gitignore

### PR DESCRIPTION
**Pull request by antoinecollet5**
Associated issue: #147 
- Add makefile at the root of the project to automate usual actions required in dev phases

### CODE REVIEW

**Comment by antoinecollet5** [comment]
I don't really get why mypy keep checking _version.py ...

**Comment by dafeda** [comment]
Do we agree that this can be closed based on the discussion around `Makefiles`?

**Comment by antoinecollet5** [comment]
Since you do not want Makefile at the root of the project, I added it to .gitignore if you are OK with that.

**Comment by dafeda** [comment]
Perhaps you can instead add it to your local .gitignore file? I don't see a reason for ignoring it in the repo to be honest.

**Pull request closed without merging**
